// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package github

import (
	"context"

	"github.com/google/go-github/v80/github"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetContentsRaw provides a mock function for the type MockClient
func (_mock *MockClient) GetContentsRaw(ctx context.Context, repo string, path string) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error) {
	ret := _mock.Called(ctx, repo, path)

	if len(ret) == 0 {
		panic("no return value specified for GetContentsRaw")
	}

	var r0 *github.RepositoryContent
	var r1 []*github.RepositoryContent
	var r2 *github.Response
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error)); ok {
		return returnFunc(ctx, repo, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *github.RepositoryContent); ok {
		r0 = returnFunc(ctx, repo, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepositoryContent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) []*github.RepositoryContent); ok {
		r1 = returnFunc(ctx, repo, path)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*github.RepositoryContent)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) *github.Response); ok {
		r2 = returnFunc(ctx, repo, path)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string, string) error); ok {
		r3 = returnFunc(ctx, repo, path)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockClient_GetContentsRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContentsRaw'
type MockClient_GetContentsRaw_Call struct {
	*mock.Call
}

// GetContentsRaw is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - path string
func (_e *MockClient_Expecter) GetContentsRaw(ctx interface{}, repo interface{}, path interface{}) *MockClient_GetContentsRaw_Call {
	return &MockClient_GetContentsRaw_Call{Call: _e.mock.On("GetContentsRaw", ctx, repo, path)}
}

func (_c *MockClient_GetContentsRaw_Call) Run(run func(ctx context.Context, repo string, path string)) *MockClient_GetContentsRaw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_GetContentsRaw_Call) Return(repositoryContent *github.RepositoryContent, repositoryContents []*github.RepositoryContent, response *github.Response, err error) *MockClient_GetContentsRaw_Call {
	_c.Call.Return(repositoryContent, repositoryContents, response, err)
	return _c
}

func (_c *MockClient_GetContentsRaw_Call) RunAndReturn(run func(ctx context.Context, repo string, path string) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error)) *MockClient_GetContentsRaw_Call {
	_c.Call.Return(run)
	return _c
}

// GetTree provides a mock function for the type MockClient
func (_mock *MockClient) GetTree(ctx context.Context, repo string, sha string, recursive bool) (*github.Tree, *github.Response, error) {
	ret := _mock.Called(ctx, repo, sha, recursive)

	if len(ret) == 0 {
		panic("no return value specified for GetTree")
	}

	var r0 *github.Tree
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) (*github.Tree, *github.Response, error)); ok {
		return returnFunc(ctx, repo, sha, recursive)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) *github.Tree); ok {
		r0 = returnFunc(ctx, repo, sha, recursive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Tree)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, bool) *github.Response); ok {
		r1 = returnFunc(ctx, repo, sha, recursive)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, bool) error); ok {
		r2 = returnFunc(ctx, repo, sha, recursive)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClient_GetTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTree'
type MockClient_GetTree_Call struct {
	*mock.Call
}

// GetTree is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - sha string
//   - recursive bool
func (_e *MockClient_Expecter) GetTree(ctx interface{}, repo interface{}, sha interface{}, recursive interface{}) *MockClient_GetTree_Call {
	return &MockClient_GetTree_Call{Call: _e.mock.On("GetTree", ctx, repo, sha, recursive)}
}

func (_c *MockClient_GetTree_Call) Run(run func(ctx context.Context, repo string, sha string, recursive bool)) *MockClient_GetTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetTree_Call) Return(tree *github.Tree, response *github.Response, err error) *MockClient_GetTree_Call {
	_c.Call.Return(tree, response, err)
	return _c
}

func (_c *MockClient_GetTree_Call) RunAndReturn(run func(ctx context.Context, repo string, sha string, recursive bool) (*github.Tree, *github.Response, error)) *MockClient_GetTree_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllRepos provides a mock function for the type MockClient
func (_mock *MockClient) ListAllRepos(ctx context.Context) ([]*github.Repository, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllRepos")
	}

	var r0 []*github.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*github.Repository, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*github.Repository); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListAllRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllRepos'
type MockClient_ListAllRepos_Call struct {
	*mock.Call
}

// ListAllRepos is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) ListAllRepos(ctx interface{}) *MockClient_ListAllRepos_Call {
	return &MockClient_ListAllRepos_Call{Call: _e.mock.On("ListAllRepos", ctx)}
}

func (_c *MockClient_ListAllRepos_Call) Run(run func(ctx context.Context)) *MockClient_ListAllRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_ListAllRepos_Call) Return(repositorys []*github.Repository, err error) *MockClient_ListAllRepos_Call {
	_c.Call.Return(repositorys, err)
	return _c
}

func (_c *MockClient_ListAllRepos_Call) RunAndReturn(run func(ctx context.Context) ([]*github.Repository, error)) *MockClient_ListAllRepos_Call {
	_c.Call.Return(run)
	return _c
}
