// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package github

import (
	"context"

	"github.com/google/go-github/v80/github"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientInterface creates a new instance of MockClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInterface {
	mock := &MockClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientInterface is an autogenerated mock type for the ClientInterface type
type MockClientInterface struct {
	mock.Mock
}

type MockClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientInterface) EXPECT() *MockClientInterface_Expecter {
	return &MockClientInterface_Expecter{mock: &_m.Mock}
}

// GetContentsRaw provides a mock function for the type MockClientInterface
func (_mock *MockClientInterface) GetContentsRaw(ctx context.Context, repo string, path string) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error) {
	ret := _mock.Called(ctx, repo, path)

	if len(ret) == 0 {
		panic("no return value specified for GetContentsRaw")
	}

	var r0 *github.RepositoryContent
	var r1 []*github.RepositoryContent
	var r2 *github.Response
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error)); ok {
		return returnFunc(ctx, repo, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *github.RepositoryContent); ok {
		r0 = returnFunc(ctx, repo, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepositoryContent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) []*github.RepositoryContent); ok {
		r1 = returnFunc(ctx, repo, path)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*github.RepositoryContent)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) *github.Response); ok {
		r2 = returnFunc(ctx, repo, path)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string, string) error); ok {
		r3 = returnFunc(ctx, repo, path)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockClientInterface_GetContentsRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContentsRaw'
type MockClientInterface_GetContentsRaw_Call struct {
	*mock.Call
}

// GetContentsRaw is a helper method to define mock.On call
//   - ctx context.Context
//   - repo string
//   - path string
func (_e *MockClientInterface_Expecter) GetContentsRaw(ctx interface{}, repo interface{}, path interface{}) *MockClientInterface_GetContentsRaw_Call {
	return &MockClientInterface_GetContentsRaw_Call{Call: _e.mock.On("GetContentsRaw", ctx, repo, path)}
}

func (_c *MockClientInterface_GetContentsRaw_Call) Run(run func(ctx context.Context, repo string, path string)) *MockClientInterface_GetContentsRaw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientInterface_GetContentsRaw_Call) Return(repositoryContent *github.RepositoryContent, repositoryContents []*github.RepositoryContent, response *github.Response, err error) *MockClientInterface_GetContentsRaw_Call {
	_c.Call.Return(repositoryContent, repositoryContents, response, err)
	return _c
}

func (_c *MockClientInterface_GetContentsRaw_Call) RunAndReturn(run func(ctx context.Context, repo string, path string) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error)) *MockClientInterface_GetContentsRaw_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllRepos provides a mock function for the type MockClientInterface
func (_mock *MockClientInterface) ListAllRepos(ctx context.Context) ([]*github.Repository, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllRepos")
	}

	var r0 []*github.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*github.Repository, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*github.Repository); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientInterface_ListAllRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllRepos'
type MockClientInterface_ListAllRepos_Call struct {
	*mock.Call
}

// ListAllRepos is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientInterface_Expecter) ListAllRepos(ctx interface{}) *MockClientInterface_ListAllRepos_Call {
	return &MockClientInterface_ListAllRepos_Call{Call: _e.mock.On("ListAllRepos", ctx)}
}

func (_c *MockClientInterface_ListAllRepos_Call) Run(run func(ctx context.Context)) *MockClientInterface_ListAllRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientInterface_ListAllRepos_Call) Return(repositorys []*github.Repository, err error) *MockClientInterface_ListAllRepos_Call {
	_c.Call.Return(repositorys, err)
	return _c
}

func (_c *MockClientInterface_ListAllRepos_Call) RunAndReturn(run func(ctx context.Context) ([]*github.Repository, error)) *MockClientInterface_ListAllRepos_Call {
	_c.Call.Return(run)
	return _c
}
