// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package github

import (
	"context"

	"github.com/google/go-github/v80/github"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGitAdapter creates a new instance of MockGitAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitAdapter {
	mock := &MockGitAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitAdapter is an autogenerated mock type for the GitAdapter type
type MockGitAdapter struct {
	mock.Mock
}

type MockGitAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitAdapter) EXPECT() *MockGitAdapter_Expecter {
	return &MockGitAdapter_Expecter{mock: &_m.Mock}
}

// GetTree provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) GetTree(ctx context.Context, owner string, repo string, sha string, recursive bool) (*github.Tree, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, sha, recursive)

	if len(ret) == 0 {
		panic("no return value specified for GetTree")
	}

	var r0 *github.Tree
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, bool) (*github.Tree, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, sha, recursive)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, bool) *github.Tree); ok {
		r0 = returnFunc(ctx, owner, repo, sha, recursive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Tree)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, bool) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, sha, recursive)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, bool) error); ok {
		r2 = returnFunc(ctx, owner, repo, sha, recursive)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGitAdapter_GetTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTree'
type MockGitAdapter_GetTree_Call struct {
	*mock.Call
}

// GetTree is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - sha string
//   - recursive bool
func (_e *MockGitAdapter_Expecter) GetTree(ctx interface{}, owner interface{}, repo interface{}, sha interface{}, recursive interface{}) *MockGitAdapter_GetTree_Call {
	return &MockGitAdapter_GetTree_Call{Call: _e.mock.On("GetTree", ctx, owner, repo, sha, recursive)}
}

func (_c *MockGitAdapter_GetTree_Call) Run(run func(ctx context.Context, owner string, repo string, sha string, recursive bool)) *MockGitAdapter_GetTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitAdapter_GetTree_Call) Return(tree *github.Tree, response *github.Response, err error) *MockGitAdapter_GetTree_Call {
	_c.Call.Return(tree, response, err)
	return _c
}

func (_c *MockGitAdapter_GetTree_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, sha string, recursive bool) (*github.Tree, *github.Response, error)) *MockGitAdapter_GetTree_Call {
	_c.Call.Return(run)
	return _c
}
