// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package github

import (
	"context"

	"github.com/google/go-github/v80/github"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPullRequestsAdapter creates a new instance of MockPullRequestsAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullRequestsAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullRequestsAdapter {
	mock := &MockPullRequestsAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPullRequestsAdapter is an autogenerated mock type for the PullRequestsAdapter type
type MockPullRequestsAdapter struct {
	mock.Mock
}

type MockPullRequestsAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPullRequestsAdapter) EXPECT() *MockPullRequestsAdapter_Expecter {
	return &MockPullRequestsAdapter_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPullRequestsAdapter
func (_mock *MockPullRequestsAdapter) Create(ctx context.Context, owner string, repo string, pull *github.NewPullRequest) (*github.PullRequest, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, pull)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *github.PullRequest
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.NewPullRequest) (*github.PullRequest, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, pull)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.NewPullRequest) *github.PullRequest); ok {
		r0 = returnFunc(ctx, owner, repo, pull)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.NewPullRequest) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, pull)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *github.NewPullRequest) error); ok {
		r2 = returnFunc(ctx, owner, repo, pull)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPullRequestsAdapter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPullRequestsAdapter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - pull *github.NewPullRequest
func (_e *MockPullRequestsAdapter_Expecter) Create(ctx interface{}, owner interface{}, repo interface{}, pull interface{}) *MockPullRequestsAdapter_Create_Call {
	return &MockPullRequestsAdapter_Create_Call{Call: _e.mock.On("Create", ctx, owner, repo, pull)}
}

func (_c *MockPullRequestsAdapter_Create_Call) Run(run func(ctx context.Context, owner string, repo string, pull *github.NewPullRequest)) *MockPullRequestsAdapter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.NewPullRequest
		if args[3] != nil {
			arg3 = args[3].(*github.NewPullRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPullRequestsAdapter_Create_Call) Return(pullRequest *github.PullRequest, response *github.Response, err error) *MockPullRequestsAdapter_Create_Call {
	_c.Call.Return(pullRequest, response, err)
	return _c
}

func (_c *MockPullRequestsAdapter_Create_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, pull *github.NewPullRequest) (*github.PullRequest, *github.Response, error)) *MockPullRequestsAdapter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockPullRequestsAdapter
func (_mock *MockPullRequestsAdapter) List(ctx context.Context, owner string, repo string, opts *github.PullRequestListOptions) ([]*github.PullRequest, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*github.PullRequest
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.PullRequestListOptions) ([]*github.PullRequest, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.PullRequestListOptions) []*github.PullRequest); ok {
		r0 = returnFunc(ctx, owner, repo, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.PullRequestListOptions) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, *github.PullRequestListOptions) error); ok {
		r2 = returnFunc(ctx, owner, repo, opts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPullRequestsAdapter_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPullRequestsAdapter_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - opts *github.PullRequestListOptions
func (_e *MockPullRequestsAdapter_Expecter) List(ctx interface{}, owner interface{}, repo interface{}, opts interface{}) *MockPullRequestsAdapter_List_Call {
	return &MockPullRequestsAdapter_List_Call{Call: _e.mock.On("List", ctx, owner, repo, opts)}
}

func (_c *MockPullRequestsAdapter_List_Call) Run(run func(ctx context.Context, owner string, repo string, opts *github.PullRequestListOptions)) *MockPullRequestsAdapter_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.PullRequestListOptions
		if args[3] != nil {
			arg3 = args[3].(*github.PullRequestListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPullRequestsAdapter_List_Call) Return(pullRequests []*github.PullRequest, response *github.Response, err error) *MockPullRequestsAdapter_List_Call {
	_c.Call.Return(pullRequests, response, err)
	return _c
}

func (_c *MockPullRequestsAdapter_List_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, opts *github.PullRequestListOptions) ([]*github.PullRequest, *github.Response, error)) *MockPullRequestsAdapter_List_Call {
	_c.Call.Return(run)
	return _c
}
