// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package github

import (
	"context"

	"github.com/google/go-github/v80/github"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReferencesAdapter creates a new instance of MockReferencesAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReferencesAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReferencesAdapter {
	mock := &MockReferencesAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReferencesAdapter is an autogenerated mock type for the ReferencesAdapter type
type MockReferencesAdapter struct {
	mock.Mock
}

type MockReferencesAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReferencesAdapter) EXPECT() *MockReferencesAdapter_Expecter {
	return &MockReferencesAdapter_Expecter{mock: &_m.Mock}
}

// CreateRef provides a mock function for the type MockReferencesAdapter
func (_mock *MockReferencesAdapter) CreateRef(ctx context.Context, owner string, repo string, ref github.CreateRef) (*github.Reference, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, ref)

	if len(ret) == 0 {
		panic("no return value specified for CreateRef")
	}

	var r0 *github.Reference
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, github.CreateRef) (*github.Reference, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, github.CreateRef) *github.Reference); ok {
		r0 = returnFunc(ctx, owner, repo, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Reference)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, github.CreateRef) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, ref)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, github.CreateRef) error); ok {
		r2 = returnFunc(ctx, owner, repo, ref)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockReferencesAdapter_CreateRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRef'
type MockReferencesAdapter_CreateRef_Call struct {
	*mock.Call
}

// CreateRef is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - ref github.CreateRef
func (_e *MockReferencesAdapter_Expecter) CreateRef(ctx interface{}, owner interface{}, repo interface{}, ref interface{}) *MockReferencesAdapter_CreateRef_Call {
	return &MockReferencesAdapter_CreateRef_Call{Call: _e.mock.On("CreateRef", ctx, owner, repo, ref)}
}

func (_c *MockReferencesAdapter_CreateRef_Call) Run(run func(ctx context.Context, owner string, repo string, ref github.CreateRef)) *MockReferencesAdapter_CreateRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 github.CreateRef
		if args[3] != nil {
			arg3 = args[3].(github.CreateRef)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReferencesAdapter_CreateRef_Call) Return(reference *github.Reference, response *github.Response, err error) *MockReferencesAdapter_CreateRef_Call {
	_c.Call.Return(reference, response, err)
	return _c
}

func (_c *MockReferencesAdapter_CreateRef_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, ref github.CreateRef) (*github.Reference, *github.Response, error)) *MockReferencesAdapter_CreateRef_Call {
	_c.Call.Return(run)
	return _c
}

// GetRef provides a mock function for the type MockReferencesAdapter
func (_mock *MockReferencesAdapter) GetRef(ctx context.Context, owner string, repo string, ref string) (*github.Reference, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, ref)

	if len(ret) == 0 {
		panic("no return value specified for GetRef")
	}

	var r0 *github.Reference
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*github.Reference, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *github.Reference); ok {
		r0 = returnFunc(ctx, owner, repo, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Reference)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, ref)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, owner, repo, ref)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockReferencesAdapter_GetRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRef'
type MockReferencesAdapter_GetRef_Call struct {
	*mock.Call
}

// GetRef is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - ref string
func (_e *MockReferencesAdapter_Expecter) GetRef(ctx interface{}, owner interface{}, repo interface{}, ref interface{}) *MockReferencesAdapter_GetRef_Call {
	return &MockReferencesAdapter_GetRef_Call{Call: _e.mock.On("GetRef", ctx, owner, repo, ref)}
}

func (_c *MockReferencesAdapter_GetRef_Call) Run(run func(ctx context.Context, owner string, repo string, ref string)) *MockReferencesAdapter_GetRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReferencesAdapter_GetRef_Call) Return(reference *github.Reference, response *github.Response, err error) *MockReferencesAdapter_GetRef_Call {
	_c.Call.Return(reference, response, err)
	return _c
}

func (_c *MockReferencesAdapter_GetRef_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, ref string) (*github.Reference, *github.Response, error)) *MockReferencesAdapter_GetRef_Call {
	_c.Call.Return(run)
	return _c
}
