// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package github

import (
	"context"

	"github.com/google/go-github/v80/github"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoriesAdapter creates a new instance of MockRepositoriesAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoriesAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoriesAdapter {
	mock := &MockRepositoriesAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoriesAdapter is an autogenerated mock type for the RepositoriesAdapter type
type MockRepositoriesAdapter struct {
	mock.Mock
}

type MockRepositoriesAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoriesAdapter) EXPECT() *MockRepositoriesAdapter_Expecter {
	return &MockRepositoriesAdapter_Expecter{mock: &_m.Mock}
}

// GetContents provides a mock function for the type MockRepositoriesAdapter
func (_mock *MockRepositoriesAdapter) GetContents(ctx context.Context, owner string, repo string, path string, opts *github.RepositoryContentGetOptions) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, path, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetContents")
	}

	var r0 *github.RepositoryContent
	var r1 []*github.RepositoryContent
	var r2 *github.Response
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, path, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) *github.RepositoryContent); ok {
		r0 = returnFunc(ctx, owner, repo, path, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.RepositoryContent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) []*github.RepositoryContent); ok {
		r1 = returnFunc(ctx, owner, repo, path, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*github.RepositoryContent)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) *github.Response); ok {
		r2 = returnFunc(ctx, owner, repo, path, opts)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) error); ok {
		r3 = returnFunc(ctx, owner, repo, path, opts)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockRepositoriesAdapter_GetContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContents'
type MockRepositoriesAdapter_GetContents_Call struct {
	*mock.Call
}

// GetContents is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - path string
//   - opts *github.RepositoryContentGetOptions
func (_e *MockRepositoriesAdapter_Expecter) GetContents(ctx interface{}, owner interface{}, repo interface{}, path interface{}, opts interface{}) *MockRepositoriesAdapter_GetContents_Call {
	return &MockRepositoriesAdapter_GetContents_Call{Call: _e.mock.On("GetContents", ctx, owner, repo, path, opts)}
}

func (_c *MockRepositoriesAdapter_GetContents_Call) Run(run func(ctx context.Context, owner string, repo string, path string, opts *github.RepositoryContentGetOptions)) *MockRepositoriesAdapter_GetContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *github.RepositoryContentGetOptions
		if args[4] != nil {
			arg4 = args[4].(*github.RepositoryContentGetOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepositoriesAdapter_GetContents_Call) Return(repositoryContent *github.RepositoryContent, repositoryContents []*github.RepositoryContent, response *github.Response, err error) *MockRepositoriesAdapter_GetContents_Call {
	_c.Call.Return(repositoryContent, repositoryContents, response, err)
	return _c
}

func (_c *MockRepositoriesAdapter_GetContents_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, path string, opts *github.RepositoryContentGetOptions) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error)) *MockRepositoriesAdapter_GetContents_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOrg provides a mock function for the type MockRepositoriesAdapter
func (_mock *MockRepositoriesAdapter) ListByOrg(ctx context.Context, org string, opts *github.RepositoryListByOrgOptions) ([]*github.Repository, *github.Response, error) {
	ret := _mock.Called(ctx, org, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrg")
	}

	var r0 []*github.Repository
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *github.RepositoryListByOrgOptions) ([]*github.Repository, *github.Response, error)); ok {
		return returnFunc(ctx, org, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *github.RepositoryListByOrgOptions) []*github.Repository); ok {
		r0 = returnFunc(ctx, org, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *github.RepositoryListByOrgOptions) *github.Response); ok {
		r1 = returnFunc(ctx, org, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, *github.RepositoryListByOrgOptions) error); ok {
		r2 = returnFunc(ctx, org, opts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepositoriesAdapter_ListByOrg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOrg'
type MockRepositoriesAdapter_ListByOrg_Call struct {
	*mock.Call
}

// ListByOrg is a helper method to define mock.On call
//   - ctx context.Context
//   - org string
//   - opts *github.RepositoryListByOrgOptions
func (_e *MockRepositoriesAdapter_Expecter) ListByOrg(ctx interface{}, org interface{}, opts interface{}) *MockRepositoriesAdapter_ListByOrg_Call {
	return &MockRepositoriesAdapter_ListByOrg_Call{Call: _e.mock.On("ListByOrg", ctx, org, opts)}
}

func (_c *MockRepositoriesAdapter_ListByOrg_Call) Run(run func(ctx context.Context, org string, opts *github.RepositoryListByOrgOptions)) *MockRepositoriesAdapter_ListByOrg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *github.RepositoryListByOrgOptions
		if args[2] != nil {
			arg2 = args[2].(*github.RepositoryListByOrgOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepositoriesAdapter_ListByOrg_Call) Return(repositorys []*github.Repository, response *github.Response, err error) *MockRepositoriesAdapter_ListByOrg_Call {
	_c.Call.Return(repositorys, response, err)
	return _c
}

func (_c *MockRepositoriesAdapter_ListByOrg_Call) RunAndReturn(run func(ctx context.Context, org string, opts *github.RepositoryListByOrgOptions) ([]*github.Repository, *github.Response, error)) *MockRepositoriesAdapter_ListByOrg_Call {
	_c.Call.Return(run)
	return _c
}
