// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package github

import (
	"context"

	"github.com/google/go-github/v80/github"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoriesService creates a new instance of MockRepositoriesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoriesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoriesService {
	mock := &MockRepositoriesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoriesService is an autogenerated mock type for the RepositoriesService type
type MockRepositoriesService struct {
	mock.Mock
}

type MockRepositoriesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoriesService) EXPECT() *MockRepositoriesService_Expecter {
	return &MockRepositoriesService_Expecter{mock: &_m.Mock}
}

// ListByOrg provides a mock function for the type MockRepositoriesService
func (_mock *MockRepositoriesService) ListByOrg(ctx context.Context, org string, opts *github.RepositoryListByOrgOptions) ([]*github.Repository, *github.Response, error) {
	ret := _mock.Called(ctx, org, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrg")
	}

	var r0 []*github.Repository
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *github.RepositoryListByOrgOptions) ([]*github.Repository, *github.Response, error)); ok {
		return returnFunc(ctx, org, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *github.RepositoryListByOrgOptions) []*github.Repository); ok {
		r0 = returnFunc(ctx, org, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *github.RepositoryListByOrgOptions) *github.Response); ok {
		r1 = returnFunc(ctx, org, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, *github.RepositoryListByOrgOptions) error); ok {
		r2 = returnFunc(ctx, org, opts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepositoriesService_ListByOrg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOrg'
type MockRepositoriesService_ListByOrg_Call struct {
	*mock.Call
}

// ListByOrg is a helper method to define mock.On call
//   - ctx context.Context
//   - org string
//   - opts *github.RepositoryListByOrgOptions
func (_e *MockRepositoriesService_Expecter) ListByOrg(ctx interface{}, org interface{}, opts interface{}) *MockRepositoriesService_ListByOrg_Call {
	return &MockRepositoriesService_ListByOrg_Call{Call: _e.mock.On("ListByOrg", ctx, org, opts)}
}

func (_c *MockRepositoriesService_ListByOrg_Call) Run(run func(ctx context.Context, org string, opts *github.RepositoryListByOrgOptions)) *MockRepositoriesService_ListByOrg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *github.RepositoryListByOrgOptions
		if args[2] != nil {
			arg2 = args[2].(*github.RepositoryListByOrgOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepositoriesService_ListByOrg_Call) Return(repositorys []*github.Repository, response *github.Response, err error) *MockRepositoriesService_ListByOrg_Call {
	_c.Call.Return(repositorys, response, err)
	return _c
}

func (_c *MockRepositoriesService_ListByOrg_Call) RunAndReturn(run func(ctx context.Context, org string, opts *github.RepositoryListByOrgOptions) ([]*github.Repository, *github.Response, error)) *MockRepositoriesService_ListByOrg_Call {
	_c.Call.Return(run)
	return _c
}
