// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tracker-tv/github-policy-bots/models"
)

// NewMockPolicyService creates a new instance of MockPolicyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPolicyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPolicyService {
	mock := &MockPolicyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPolicyService is an autogenerated mock type for the PolicyService type
type MockPolicyService struct {
	mock.Mock
}

type MockPolicyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPolicyService) EXPECT() *MockPolicyService_Expecter {
	return &MockPolicyService_Expecter{mock: &_m.Mock}
}

// Ensure provides a mock function for the type MockPolicyService
func (_mock *MockPolicyService) Ensure(ctx context.Context, repo models.Repository, repoFiles []string) ([]models.PolicyViolation, error) {
	ret := _mock.Called(ctx, repo, repoFiles)

	if len(ret) == 0 {
		panic("no return value specified for Ensure")
	}

	var r0 []models.PolicyViolation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Repository, []string) ([]models.PolicyViolation, error)); ok {
		return returnFunc(ctx, repo, repoFiles)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Repository, []string) []models.PolicyViolation); ok {
		r0 = returnFunc(ctx, repo, repoFiles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PolicyViolation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Repository, []string) error); ok {
		r1 = returnFunc(ctx, repo, repoFiles)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPolicyService_Ensure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ensure'
type MockPolicyService_Ensure_Call struct {
	*mock.Call
}

// Ensure is a helper method to define mock.On call
//   - ctx context.Context
//   - repo models.Repository
//   - repoFiles []string
func (_e *MockPolicyService_Expecter) Ensure(ctx interface{}, repo interface{}, repoFiles interface{}) *MockPolicyService_Ensure_Call {
	return &MockPolicyService_Ensure_Call{Call: _e.mock.On("Ensure", ctx, repo, repoFiles)}
}

func (_c *MockPolicyService_Ensure_Call) Run(run func(ctx context.Context, repo models.Repository, repoFiles []string)) *MockPolicyService_Ensure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Repository
		if args[1] != nil {
			arg1 = args[1].(models.Repository)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPolicyService_Ensure_Call) Return(policyViolations []models.PolicyViolation, err error) *MockPolicyService_Ensure_Call {
	_c.Call.Return(policyViolations, err)
	return _c
}

func (_c *MockPolicyService_Ensure_Call) RunAndReturn(run func(ctx context.Context, repo models.Repository, repoFiles []string) ([]models.PolicyViolation, error)) *MockPolicyService_Ensure_Call {
	_c.Call.Return(run)
	return _c
}
