// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tracker-tv/github-policy-bots/internal/service"
	"github.com/tracker-tv/github-policy-bots/models"
)

// NewMockRemediationService creates a new instance of MockRemediationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemediationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemediationService {
	mock := &MockRemediationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRemediationService is an autogenerated mock type for the RemediationService type
type MockRemediationService struct {
	mock.Mock
}

type MockRemediationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemediationService) EXPECT() *MockRemediationService_Expecter {
	return &MockRemediationService_Expecter{mock: &_m.Mock}
}

// Remediate provides a mock function for the type MockRemediationService
func (_mock *MockRemediationService) Remediate(ctx context.Context, drift models.PolicyDeviation) (*service.RemediationResult, error) {
	ret := _mock.Called(ctx, drift)

	if len(ret) == 0 {
		panic("no return value specified for Remediate")
	}

	var r0 *service.RemediationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.PolicyDeviation) (*service.RemediationResult, error)); ok {
		return returnFunc(ctx, drift)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.PolicyDeviation) *service.RemediationResult); ok {
		r0 = returnFunc(ctx, drift)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.RemediationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.PolicyDeviation) error); ok {
		r1 = returnFunc(ctx, drift)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRemediationService_Remediate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remediate'
type MockRemediationService_Remediate_Call struct {
	*mock.Call
}

// Remediate is a helper method to define mock.On call
//   - ctx context.Context
//   - drift models.PolicyDeviation
func (_e *MockRemediationService_Expecter) Remediate(ctx interface{}, drift interface{}) *MockRemediationService_Remediate_Call {
	return &MockRemediationService_Remediate_Call{Call: _e.mock.On("Remediate", ctx, drift)}
}

func (_c *MockRemediationService_Remediate_Call) Run(run func(ctx context.Context, drift models.PolicyDeviation)) *MockRemediationService_Remediate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.PolicyDeviation
		if args[1] != nil {
			arg1 = args[1].(models.PolicyDeviation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRemediationService_Remediate_Call) Return(remediationResult *service.RemediationResult, err error) *MockRemediationService_Remediate_Call {
	_c.Call.Return(remediationResult, err)
	return _c
}

func (_c *MockRemediationService_Remediate_Call) RunAndReturn(run func(ctx context.Context, drift models.PolicyDeviation) (*service.RemediationResult, error)) *MockRemediationService_Remediate_Call {
	_c.Call.Return(run)
	return _c
}
