// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tracker-tv/github-policy-bots/models"
)

// NewMockRepositoryService creates a new instance of MockRepositoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryService {
	mock := &MockRepositoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryService is an autogenerated mock type for the RepositoryService type
type MockRepositoryService struct {
	mock.Mock
}

type MockRepositoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryService) EXPECT() *MockRepositoryService_Expecter {
	return &MockRepositoryService_Expecter{mock: &_m.Mock}
}

// ListAll provides a mock function for the type MockRepositoryService
func (_mock *MockRepositoryService) ListAll(ctx context.Context) ([]models.Repository, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []models.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Repository, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Repository); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryService_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockRepositoryService_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepositoryService_Expecter) ListAll(ctx interface{}) *MockRepositoryService_ListAll_Call {
	return &MockRepositoryService_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockRepositoryService_ListAll_Call) Run(run func(ctx context.Context)) *MockRepositoryService_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryService_ListAll_Call) Return(repositorys []models.Repository, err error) *MockRepositoryService_ListAll_Call {
	_c.Call.Return(repositorys, err)
	return _c
}

func (_c *MockRepositoryService_ListAll_Call) RunAndReturn(run func(ctx context.Context) ([]models.Repository, error)) *MockRepositoryService_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiles provides a mock function for the type MockRepositoryService
func (_mock *MockRepositoryService) ListFiles(ctx context.Context, repoName string) ([]string, error) {
	ret := _mock.Called(ctx, repoName)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, repoName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, repoName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryService_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type MockRepositoryService_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - repoName string
func (_e *MockRepositoryService_Expecter) ListFiles(ctx interface{}, repoName interface{}) *MockRepositoryService_ListFiles_Call {
	return &MockRepositoryService_ListFiles_Call{Call: _e.mock.On("ListFiles", ctx, repoName)}
}

func (_c *MockRepositoryService_ListFiles_Call) Run(run func(ctx context.Context, repoName string)) *MockRepositoryService_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryService_ListFiles_Call) Return(strings []string, err error) *MockRepositoryService_ListFiles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockRepositoryService_ListFiles_Call) RunAndReturn(run func(ctx context.Context, repoName string) ([]string, error)) *MockRepositoryService_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}
